name: Build
on: [push, pull_request]

jobs:
  checks:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with meson
        run: |
          pip install meson
          
          meson setup build
          meson compile -C build

      - name: Test with meson
        run: |
          meson test -C build
